/*
 * MainFrame.java
 *
 * Created on 26 de noviembre de 2008, 15:59
 */

package com.rgonzalez.robustez.estimadores.tarea2;

import com.rgonzalez.robustez.estimadores.tarea2.panel.MuPanel;
import com.rgonzalez.robustez.estimadores.tarea2.panel.MuSigmaPanel;
import com.rgonzalez.robustez.estimadores.tarea2.panel.SigmaPanel;
import org.jfree.ui.RefineryUtilities;

/**
 * Clase principal
 * @author  Administrador
 */
public class MainFrame extends javax.swing.JFrame {

    public static final double data[] = {
        2.20, 2.20, 2.40, 2.40, 2.50, 2.70,
        2.80, 2.90, 3.03, 3.03, 3.10, 3.37,
        3.40, 3.40, 3.40, 3.50, 3.60, 3.70,
        3.70, 3.70, 3.70, 3.77, 5.28, 28.95
    };
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setTitle("Robust Huber");
        this.tabbed.addTab("Mu", new MuPanel());
        this.tabbed.addTab("Sigma", new SigmaPanel());
        this.tabbed.addTab("Simultaneous", new MuSigmaPanel());
        
        this.textPromedio.setText(Double.toString(Statistic.getMean(data)));
        this.textMediana.setText(Double.toString(Statistic.getMedian(data)));
        this.textDesvStd.setText(Double.toString(Statistic.getStdDesv(data)));
        this.textMadn.setText(Double.toString(Statistic.getMadn(data)));
        this.pack();
        RefineryUtilities.centerFrameOnScreen(this);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed = new javax.swing.JTabbedPane();
        panelNorth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textPromedio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textMediana = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textDesvStd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textMadn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(tabbed, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Promedio: ");
        panelNorth.add(jLabel2);

        textPromedio.setText("<Promedio>");
        panelNorth.add(textPromedio);

        jLabel6.setText("              ");
        panelNorth.add(jLabel6);

        jLabel4.setText("Mediana: ");
        panelNorth.add(jLabel4);

        textMediana.setText("<Mediana>");
        panelNorth.add(textMediana);

        jLabel7.setText("               ");
        panelNorth.add(jLabel7);

        jLabel5.setText("Desv.Std: ");
        panelNorth.add(jLabel5);

        textDesvStd.setText("<Desv.Std>");
        panelNorth.add(textDesvStd);

        jLabel8.setText("                 ");
        panelNorth.add(jLabel8);

        jLabel9.setText("MADN");
        panelNorth.add(jLabel9);

        textMadn.setText("<Desv.Std>");
        panelNorth.add(textMadn);

        getContentPane().add(panelNorth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JLabel textDesvStd;
    private javax.swing.JLabel textMadn;
    private javax.swing.JLabel textMediana;
    private javax.swing.JLabel textPromedio;
    // End of variables declaration//GEN-END:variables

}
