/*
 * MesuresDialog.java
 *
 * Created on 27 de julio de 2008, 1:09
 */

package com.rgonzalez.colas.gui;

import com.rgonzalez.colas.fel.SimulacionFEL;
import javax.swing.JDialog;

/**
 * Esta ventana solo presenta los indicadores del sistema.
 * @author  Administrador
 */
public class MesuresDialog extends javax.swing.JDialog {

    /** 
     * Constructor de MesuresDialog
     */
    public MesuresDialog(JDialog parent, boolean modal, SimulacionFEL simulacion) {
        super(parent, "Medidads del Sistema", modal);
        initComponents();
        
        this.textTiempoMedioCola.setText( Double.toString( simulacion.getT_medio_cola() ) );
        this.textTiempoMedioServidor.setText( Double.toString( simulacion.getT_medio_servidor() ) );
        this.textTiempoMedioSistema.setText( Double.toString( simulacion.getT_medio_sistema() ) );
        this.textNumeroMedioCola.setText( Double.toString( simulacion.getN_medio_cola()) );
        this.textNumeroMedioServidor.setText( Double.toString( simulacion.getN_medio_servidor() ) );
        this.textNumeroMedioSistema.setText( Double.toString( simulacion.getN_medio_sistema()) ); 
        this.textPorcentajeOcupacion.setText( Double.toString( simulacion.getPorcentaje()) );
        
        this.pack();
        Util.center(this);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * Metodo autogenerado por Netbeans para crear los componentes
     * iniciales de la ventana.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        panelLabelTiempoMedioCola = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTextTiempoMedioCola = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textTiempoMedioCola = new javax.swing.JLabel();
        panelLabelTiempoMedioServidor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelTextTiempoMedioServidor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textTiempoMedioServidor = new javax.swing.JLabel();
        panelLabelTiempoMedioSistema = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelTextTiempoMedioSistema = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textTiempoMedioSistema = new javax.swing.JLabel();
        panelLabelNumeroMedioCola = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelTextNumeroMedioCola = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textNumeroMedioCola = new javax.swing.JLabel();
        panelLabelNumeroMedioServidor = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panelTextNumeroMedioServidor = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textNumeroMedioServidor = new javax.swing.JLabel();
        panelLabelNumeroMedioSistema = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelTextNumeroMedioSistema = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        textNumeroMedioSistema = new javax.swing.JLabel();
        panelLabelPorcentajeOcupacion = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelTextlPorcentajeOcupacion = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textPorcentajeOcupacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelSouth = new javax.swing.JPanel();
        buttonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));
        panelCenter.setLayout(new java.awt.GridLayout(7, 2));

        panelLabelTiempoMedioCola.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Tiempo Medio Cola Espera");
        panelLabelTiempoMedioCola.add(jLabel1);

        panelCenter.add(panelLabelTiempoMedioCola);

        panelTextTiempoMedioCola.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText(": ");
        panelTextTiempoMedioCola.add(jLabel4);

        textTiempoMedioCola.setText("<>");
        panelTextTiempoMedioCola.add(textTiempoMedioCola);

        panelCenter.add(panelTextTiempoMedioCola);

        panelLabelTiempoMedioServidor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Tiempo Medio en Servidor");
        panelLabelTiempoMedioServidor.add(jLabel3);

        panelCenter.add(panelLabelTiempoMedioServidor);

        panelTextTiempoMedioServidor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText(": ");
        panelTextTiempoMedioServidor.add(jLabel6);

        textTiempoMedioServidor.setText("<>");
        panelTextTiempoMedioServidor.add(textTiempoMedioServidor);

        panelCenter.add(panelTextTiempoMedioServidor);

        panelLabelTiempoMedioSistema.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Tiempo Medio en Sistema");
        panelLabelTiempoMedioSistema.add(jLabel5);

        panelCenter.add(panelLabelTiempoMedioSistema);

        panelTextTiempoMedioSistema.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText(": ");
        panelTextTiempoMedioSistema.add(jLabel8);

        textTiempoMedioSistema.setText("<>");
        panelTextTiempoMedioSistema.add(textTiempoMedioSistema);

        panelCenter.add(panelTextTiempoMedioSistema);

        panelLabelNumeroMedioCola.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("Numero Medio Cola Espera");
        panelLabelNumeroMedioCola.add(jLabel7);

        panelCenter.add(panelLabelNumeroMedioCola);

        panelTextNumeroMedioCola.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setText(": ");
        panelTextNumeroMedioCola.add(jLabel10);

        textNumeroMedioCola.setText("<>");
        panelTextNumeroMedioCola.add(textNumeroMedioCola);

        panelCenter.add(panelTextNumeroMedioCola);

        panelLabelNumeroMedioServidor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Numero Medio En Servidor");
        panelLabelNumeroMedioServidor.add(jLabel9);

        panelCenter.add(panelLabelNumeroMedioServidor);

        panelTextNumeroMedioServidor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel12.setText(": ");
        panelTextNumeroMedioServidor.add(jLabel12);

        textNumeroMedioServidor.setText("<>");
        panelTextNumeroMedioServidor.add(textNumeroMedioServidor);

        panelCenter.add(panelTextNumeroMedioServidor);

        panelLabelNumeroMedioSistema.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setText("Numero Medio En Sistema");
        panelLabelNumeroMedioSistema.add(jLabel11);

        panelCenter.add(panelLabelNumeroMedioSistema);

        panelTextNumeroMedioSistema.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel14.setText(": ");
        panelTextNumeroMedioSistema.add(jLabel14);

        textNumeroMedioSistema.setText("<>");
        panelTextNumeroMedioSistema.add(textNumeroMedioSistema);

        panelCenter.add(panelTextNumeroMedioSistema);

        panelLabelPorcentajeOcupacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel13.setText("Porcentaje Ocupacion Servidor");
        panelLabelPorcentajeOcupacion.add(jLabel13);

        panelCenter.add(panelLabelPorcentajeOcupacion);

        panelTextlPorcentajeOcupacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel15.setText(": ");
        panelTextlPorcentajeOcupacion.add(jLabel15);

        textPorcentajeOcupacion.setText("<>");
        panelTextlPorcentajeOcupacion.add(textPorcentajeOcupacion);

        jLabel2.setText("%");
        panelTextlPorcentajeOcupacion.add(jLabel2);

        panelCenter.add(panelTextlPorcentajeOcupacion);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonClose.setText("Cerrar");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        panelSouth.add(buttonClose);

        getContentPane().add(panelSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
/**
 * Se cierra la ventana al apretarn el boton "Cerrar".
 * @param evt El evento.
 */
private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
    this.dispose();
}//GEN-LAST:event_buttonCloseActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLabelNumeroMedioCola;
    private javax.swing.JPanel panelLabelNumeroMedioServidor;
    private javax.swing.JPanel panelLabelNumeroMedioSistema;
    private javax.swing.JPanel panelLabelPorcentajeOcupacion;
    private javax.swing.JPanel panelLabelTiempoMedioCola;
    private javax.swing.JPanel panelLabelTiempoMedioServidor;
    private javax.swing.JPanel panelLabelTiempoMedioSistema;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JPanel panelTextNumeroMedioCola;
    private javax.swing.JPanel panelTextNumeroMedioServidor;
    private javax.swing.JPanel panelTextNumeroMedioSistema;
    private javax.swing.JPanel panelTextTiempoMedioCola;
    private javax.swing.JPanel panelTextTiempoMedioServidor;
    private javax.swing.JPanel panelTextTiempoMedioSistema;
    private javax.swing.JPanel panelTextlPorcentajeOcupacion;
    private javax.swing.JLabel textNumeroMedioCola;
    private javax.swing.JLabel textNumeroMedioServidor;
    private javax.swing.JLabel textNumeroMedioSistema;
    private javax.swing.JLabel textPorcentajeOcupacion;
    private javax.swing.JLabel textTiempoMedioCola;
    private javax.swing.JLabel textTiempoMedioServidor;
    private javax.swing.JLabel textTiempoMedioSistema;
    // End of variables declaration//GEN-END:variables

}
