/*
 * MainRegresionFrame.java
 *
 * Created on 29 de diciembre de 2008, 18:20
 */

package com.gonzalez.aida.main;

import com.gonzalez.aida.ann.RegresionNN;
import com.gonzalez.aida.dataset.BostonDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author  Administrador
 */
public class MainRegresionFrame extends javax.swing.JFrame {

    /** Creates new form MainRegresionFrame */
    public MainRegresionFrame() {
        initComponents();
        
        BostonDataset data = new BostonDataset("boston.data");
        RegresionNN rnn = new RegresionNN(data.getColumns(), 5, 0.3);
        double[][] error = rnn.trainWith(4000, data);
        
        this.panelCenter.add(new PlotFunctionPanel(error, "Error", "Iteracion", "Error", 0));
        pack();
        RefineryUtilities.centerFrameOnScreen(this);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCenter.setLayout(new javax.swing.BoxLayout(panelCenter, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainRegresionFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCenter;
    // End of variables declaration//GEN-END:variables

}
