/*
 * MuSigmaPanel.java
 *
 * Created on 27 de noviembre de 2008, 19:10
 */
package com.rgonzalez.robustez.estimadores.tarea2.panel;

import com.rgonzalez.robustez.estimadores.tarea2.estimators.MuSigmaEstimator;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrador
 */
public class MuSigmaPanel extends javax.swing.JPanel {

    private double delta = 0.99;
    private int K = 30;
    private MuSigmaEstimator muSigma;
    private PlotFunctionPanel panelMuPlot;
    private PlotFunctionPanel panelSigmaPlot;

    /** Creates new form MuSigmaPanel */
    public MuSigmaPanel() {
        initComponents();
        
        this.textDelta.setText(Double.toString(delta));
        this.textK.setText(Integer.toString(K));
        muSigma = new MuSigmaEstimator(delta, K);
        panelMuPlot = new PlotFunctionPanel(muSigma.getMuData(), "k-Huber vs Mu", "k-Huber", "Mu");
        panelSigmaPlot = new PlotFunctionPanel(muSigma.getSigmaData(), "k-Huber vs Sigma", "k-Huber", "Sigma");
        this.muPanel.add(panelMuPlot);
        this.sigmaPanel.add(panelSigmaPlot);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUpdate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textDelta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonUpdate = new javax.swing.JButton();
        tabbed = new javax.swing.JTabbedPane();
        muPanel = new javax.swing.JPanel();
        sigmaPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel2.setText("iteraciones");
        panelUpdate.add(jLabel2);

        textK.setPreferredSize(new java.awt.Dimension(60, 20));
        textK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKActionPerformed(evt);
            }
        });
        panelUpdate.add(textK);

        jLabel4.setText("      ");
        panelUpdate.add(jLabel4);

        jLabel1.setText("delta");
        panelUpdate.add(jLabel1);

        textDelta.setPreferredSize(new java.awt.Dimension(60, 20));
        textDelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeltaActionPerformed(evt);
            }
        });
        panelUpdate.add(textDelta);

        jLabel3.setText("      ");
        panelUpdate.add(jLabel3);

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        panelUpdate.add(buttonUpdate);

        add(panelUpdate, java.awt.BorderLayout.SOUTH);

        tabbed.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        muPanel.setLayout(new javax.swing.BoxLayout(muPanel, javax.swing.BoxLayout.LINE_AXIS));
        tabbed.addTab("Mu", muPanel);

        sigmaPanel.setLayout(new javax.swing.BoxLayout(sigmaPanel, javax.swing.BoxLayout.LINE_AXIS));
        tabbed.addTab("Sigma", sigmaPanel);

        add(tabbed, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void textDeltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeltaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_textDeltaActionPerformed

private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
    try {
        double myDelta = Double.parseDouble(this.textDelta.getText());
        int myK = Integer.parseInt(this.textK.getText());

        System.out.println(myK);
        if (delta > 1 || delta <= 0) {
            JOptionPane.showMessageDialog(this, "Delta fuera rango [0,1]", "Cholga", JOptionPane.WARNING_MESSAGE);
        } else {
            delta = myDelta;
            K = myK;
            muSigma.update(delta, K);
            panelMuPlot.update(muSigma.getMuData());
            panelSigmaPlot.update(muSigma.getSigmaData());
            panelMuPlot.updateUI();
            panelSigmaPlot.updateUI();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Se ha capturado una cholga", "Cholga", JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_buttonUpdateActionPerformed

private void textKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_textKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel muPanel;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel sigmaPanel;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTextField textDelta;
    private javax.swing.JTextField textK;
    // End of variables declaration//GEN-END:variables
}
