/*
 * SigmaPanel.java
 *
 * Created on 27 de noviembre de 2008, 18:44
 */
package com.rgonzalez.robustez.estimadores.tarea2.panel;

import com.rgonzalez.robustez.estimadores.tarea2.estimators.SigmaEstimator;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrador
 */
public class SigmaPanel extends javax.swing.JPanel {

    private PlotFunctionPanel panelPlot;
    private SigmaEstimator sigma;
    private double delta = 0.4;
    private double epsilon = 0.01;

    /** Creates new form SigmaPanel */
    public SigmaPanel() {
        initComponents();

        this.textEpsilon.setText(Double.toString(epsilon));
        this.textDelta.setText(Double.toString(delta));
        sigma = new SigmaEstimator(epsilon, delta);
        panelPlot = new PlotFunctionPanel(sigma.getData(), "k-Huber vs Sigma", "k-Huber", "Sigma");
        this.mainPanel.add(panelPlot);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelUpdate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textEpsilon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textDelta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonUpdate = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());
        add(mainPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("epsilon");
        panelUpdate.add(jLabel1);

        textEpsilon.setPreferredSize(new java.awt.Dimension(60, 20));
        textEpsilon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEpsilonActionPerformed(evt);
            }
        });
        panelUpdate.add(textEpsilon);

        jLabel3.setText("      ");
        panelUpdate.add(jLabel3);

        jLabel2.setText("delta");
        panelUpdate.add(jLabel2);

        textDelta.setMinimumSize(new java.awt.Dimension(20, 20));
        textDelta.setPreferredSize(new java.awt.Dimension(60, 20));
        panelUpdate.add(textDelta);

        jLabel4.setText("      ");
        panelUpdate.add(jLabel4);

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        panelUpdate.add(buttonUpdate);

        add(panelUpdate, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

private void textEpsilonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEpsilonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_textEpsilonActionPerformed

private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
    try {
        double myEpsilon = Double.parseDouble(this.textEpsilon.getText());
        double myDelta = Double.parseDouble(this.textDelta.getText());
        if (myEpsilon > 1 || myEpsilon <= 0) {
            JOptionPane.showMessageDialog(this, "Valor epsilon incorrecto", "Cholga", JOptionPane.WARNING_MESSAGE);
        } else if(myDelta > 1 || myDelta <= 0){
            JOptionPane.showMessageDialog(this, "Valor sigma incorrecto", "Cholga", JOptionPane.WARNING_MESSAGE);
        }
        else{
            epsilon = myEpsilon;
            delta = myDelta;
            sigma.update(epsilon,delta);
            panelPlot.update(sigma.getData());
            panelPlot.updateUI();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Se ha capturado una cholga", "Cholga", JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_buttonUpdateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTextField textDelta;
    private javax.swing.JTextField textEpsilon;
    // End of variables declaration//GEN-END:variables
}
